#!/bin/sh
set -e

ln -sf /dev/stdout /var/log/apache2/error.log
ln -sf /dev/stdout /var/log/apache2/access.log

sed -i 's/ServerSignature On/ServerSignature Off/g' /etc/apache2/conf-enabled/security.conf

exec /usr/sbin/apachectl -D FOREGROUND

#ping 8.8.8.8
