#!/bin/bash

echo "--------- Apt-get update ---------"
apt-get update
echo "--------- Ibstalling sudo vim ---------"
apt-get -y install sudo vim mysql-client wget

echo "--------- Installing composer ---------"
/usr/bin/php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
# /usr/bin/php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
/usr/bin/php composer-setup.php --install-dir=/bin --filename=composer
/usr/bin/php -r "unlink('composer-setup.php');"

cd $WORKDIR/$APP_FOLDER/public/

cp $WORKDIR/$APP_FOLDER/.env.example $WORKDIR/$APP_FOLDER/.env
cd $WORKDIR/$APP_FOLDER
sudo -u usr1 /bin/composer update
/usr/bin/php artisan key:generate
sed -i "s/DB_HOST=.*/DB_HOST=$MYSQL_HOST/" $WORKDIR/$APP_FOLDER/.env
sed -i "s/DB_DATABASE=.*/DB_DATABASE=$MYSQL_DATABASE/g" $WORKDIR/$APP_FOLDER/.env
sed -i "s/DB_USERNAME=.*/DB_USERNAME=$MYSQL_USER/" $WORKDIR/$APP_FOLDER/.env
sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=$MYSQL_PASSWORD/" $WORKDIR/$APP_FOLDER/.env
sed -i "s#.*DocumentRoot.*#DocumentRoot $WORKDIR/$APP_FOLDER/public#g" /etc/apache2/sites-enabled/000-default.conf

apt-get install -y apt-transport-https lsb-release ca-certificates
if [ ! -f /etc/apt/trusted.gpg.d/php.gpg ]; then 
    wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
fi
if [ ! -f /etc/apt/sources.list.d/php.list ]; then
    echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list
fi

PHP_VERSION=7.3
apt-get update 
apt-get -y install php$PHP_VERSION php$PHP_VERSION-mbstring php$PHP_VERSION-xml php$PHP_VERSION-zip php$PHP_VERSION-mysql php$PHP_VERSION-bcmath php$PHP_VERSION-gd php$PHP_VERSION-common php$PHP_VERSION-curl php$PHP_VERSION-intl

a2dismod php7.0
a2enmod php$PHP_VERSION

## Leave this at the end or following commands will not excecute
echo "--------- Reload Apache ---------" 
exec /usr/sbin/apachectl -k graceful

